sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/src/Entity/Equipe.php
<?php

namespace App\Entity;

use App\Repository\EquipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EquipeRepository::class)]
class Equipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\Column(length: 255)]
    private ?string $entraineur = null;

    #[ORM\Column(length: 255)]
    private ?string $creneaux = null;

    #[ORM\Column(length: 255)]
    private ?string $url_photo = null;

    #[ORM\Column(length: 255)]
    private ?string $url_result_calendrier = null;

    #[ORM\Column(length: 2048)]
    private ?string $commentaire = null;

    #[ORM\OneToMany(mappedBy: 'equipe_locale', targetEntity: Rencontre::class)]
    private Collection $rencontres;

    public function __construct()
    {
        $this->rencontres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getEntraineur(): ?string
    {
        return $this->entraineur;
    }

    public function setEntraineur(string $entraineur): self
    {
        $this->entraineur = $entraineur;

        return $this;
    }

    public function getCreneaux(): ?string
    {
        return $this->creneaux;
    }

    public function setCreneaux(string $creneaux): self
    {
        $this->creneaux = $creneaux;

        return $this;
    }

    public function getUrlPhoto(): ?string
    {
        return $this->url_photo;
    }

    public function setUrlPhoto(string $url_photo): self
    {
        $this->url_photo = $url_photo;

        return $this;
    }

    public function getUrlResultCalendrier(): ?string
    {
        return $this->url_result_calendrier;
    }

    public function setUrlResultCalendrier(string $url_result_calendrier): self
    {
        $this->url_result_calendrier = $url_result_calendrier;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * @return Collection<int, Rencontre>
     */
    public function getRencontres(): Collection
    {
        return $this->rencontres;
    }

    public function addRencontre(Rencontre $rencontre): self
    {
        if (!$this->rencontres->contains($rencontre)) {
            $this->rencontres->add($rencontre);
            $rencontre->setEquipeLocale($this);
        }

        return $this;
    }

    public function removeRencontre(Rencontre $rencontre): self
    {
        if ($this->rencontres->removeElement($rencontre)) {
            // set the owning side to null (unless already changed)
            if ($rencontre->getEquipeLocale() === $this) {
                $rencontre->setEquipeLocale(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getLibelle();
    }
}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/src/Form/EquipeType.php
<?php

namespace App\Form;

use App\Entity\Equipe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class EquipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle')
            ->add('entraineur')
            ->add('creneaux')
            ->add('url_photo',FileType::class,[
                'mapped'=>false,'required'=>false,
                    'constraints'=>[new Image()]
                    ])
            ->add('url_result_calendrier',FileType::class,['mapped'=>false,'required'=>false,
            'constraints'=>[new Image()]
            ])
            ->add('commentaire')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Equipe::class,
        ]);
    }
}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/src/Controller/EquipeController.php
<?php

namespace App\Controller;

use App\Entity\Equipe;
use App\Form\EquipeType;
use App\Repository\EquipeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/equipe')]
class EquipeController extends AbstractController
{
    #[Route('/', name: 'app_equipe_index', methods: ['GET'])]
    public function index(EquipeRepository $equipeRepository): Response
    {
        return $this->render('equipe/index.html.twig', [
            'equipes' => $equipeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_equipe_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EquipeRepository $equipeRepository): Response
    {
        $equipe = new Equipe();
        $form = $this->createForm(EquipeType::class, $equipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            //Get the image 
            $url_photo = $form->get('url_photo')->getData();
            $url_result = $form->get('url_result_calendrier')->getData();
            //Copy the image
            $path= $this->getParameter('kernel.project_dir');
            $photo_relatif = "/public/image/".explode("/",$url_photo)[2]; 
            $result_relatif = "/public/image/".explode("/",$url_result)[2];
            $url_photo_new_place = $path.$photo_relatif; 
            $url_result_new_place = $path.$result_relatif; 
            copy($url_photo,$url_photo_new_place);
            copy($url_result,$url_result_new_place);
            //Set the image in $equipe 
            $data->setUrlPhoto($photo_relatif);
            $data->setUrlResultCalendrier($result_relatif);

            $equipeRepository->save($equipe, true);

            return $this->redirectToRoute('app_equipe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('equipe/new.html.twig', [
            'equipe' => $equipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_equipe_show', methods: ['GET'])]
    public function show(Equipe $equipe): Response
    {
        $photo= $equipe->getUrlPhoto();
        $resultat = $equipe->getUrlResultCalendrier();
        return $this->render('equipe/show.html.twig', [
            'resultat' => $resultat,
            'photo' => $photo,
            'equipe' => $equipe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_equipe_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Equipe $equipe, EquipeRepository $equipeRepository): Response
    {
        $form = $this->createForm(EquipeType::class, $equipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            //Get the image 
            $url_photo = $form->get('url_photo')->getData();
            $url_result = $form->get('url_result_calendrier')->getData();
            //Copy the image
            $path= $this->getParameter('kernel.project_dir');
            if($url_photo){

            $tpm= explode("/",$url_photo); 
            $photo_relatif = "/public/image/".end($tpm); 
            $url_photo_new_place = $path.$photo_relatif;           
            copy($url_photo,$url_photo_new_place);
            $data->setUrlPhoto($photo_relatif);
            }

            if($url_result){
            $tpm= explode("/",$url_result); 
            $result_relatif = "/public/image/".end($tpm);
            $url_result_new_place = $path.$result_relatif;
            copy($url_result,$url_result_new_place);
            $data->setUrlResultCalendrier($result_relatif);
            }

            $equipeRepository->save($equipe, true);

            return $this->redirectToRoute('app_equipe_index', [], Response::HTTP_SEE_OTHER);
        }
        $path= $this->getParameter('kernel.project_dir');
        $url_photo = $equipe->getUrlPhoto();
        $photo = new File($path.$url_photo);
        $url_result = $equipe->getUrlResultCalendrier();
        $resultat = new File($path.$url_result);
        return $this->renderForm('equipe/edit.html.twig', [
            'resultat' => $resultat,
            'photo' => $photo,
            'equipe' => $equipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_equipe_delete', methods: ['POST'])]
    public function delete(Request $request, Equipe $equipe, EquipeRepository $equipeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$equipe->getId(), $request->request->get('_token'))) {
            $equipeRepository->remove($equipe, true);
        }

        return $this->redirectToRoute('app_equipe_index', [], Response::HTTP_SEE_OTHER);
    }
}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/equipe/_delete_form.html.twig
<form method="post" action="{{ path('app_equipe_delete', {'id': equipe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ equipe.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/equipe/_form.html.twig
{{ form_start(form) }}
    <div class="form mx-3 my-auto">
        <div class="form-group">
            {{ form_label(form.libelle) }}
            {{ form_widget(form.libelle, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.entraineur) }}
            {{ form_widget(form.entraineur, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.creneaux) }}
            {{ form_widget(form.creneaux, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.url_photo) }}
            {{ form_widget(form.url_photo, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.url_result_calendrier) }}
            {{ form_widget(form.url_result_calendrier, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.commentaire) }}
            {{ form_widget(form.commentaire, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="d-flex flex-row-reverse px-2 justify-content-space-around py-2">
            <button class="btn btn-success d-flex flex-row-reverse mx-2">{{ button_label|default('Save') }}</button>
            <a class="btn btn-secondary" href="{{ path('app_equipe_index') }}">Retour à la liste</a>
        </div>
    </div>
{{ form_end(form) }}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/equipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'équipe{% endblock %}

{% block body %}
    <div class="d-flex flex-justify-content-center">
        <h1 class="display-1 border border-dark rounded mx-auto mt-2 p-2">Modifier l'équipe</h1>
    </div>

    {{ include('equipe/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/equipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des équipes{% endblock %}

{% block body %}
    <div class="d-flex flex-justify-content-center">
        <h1 class="display-1 border border-dark rounded mx-auto mt-2 p-2">Liste des équipes</h1>
    </div>

    {% if is_granted('ROLE_USER') %}
        <a class="btn btn-outline-primary py-2 my-3" href="{{ path('app_equipe_new') }}">Créer une nouvelle équipe</a>
    {% endif %}
    
    <div class="tablefixHead">
    <table class="table table-striped">
        <thead>
            <tr class="table-primary">
                <th>Ids</th>
                <th>Libelles</th>
                <th>Entraineurs</th>
                <th>Créneaux</th>
                <th>Liens photo</th>
                <th>Liens calendrier</th>
                <th>Commentaires</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for equipe in equipes %}
            <tr class="my-auto">
                <td class="align-middle">{{ equipe.id }}</td>
                <td class="align-middle">{{ equipe.libelle }}</td>
                <td class="align-middle">{{ equipe.entraineur }}</td>
                <td class="align-middle">{{ equipe.creneaux }}</td>
                <td class="align-middle">{{ equipe.urlPhoto }}</td>
                <td class="align-middle">{{ equipe.urlResultCalendrier }}</td>
                <td class="align-middle">{{ equipe.commentaire }}</td>
                <td class="align-middle">
                    <div class="d-flex flex-column flex-justify-content-center flex-align-item-space-around">
                        <a class="btn btn-outline-primary" href="{{ path('app_equipe_show', {'id': equipe.id}) }}">Afficher</a>
                        {% if is_granted('ROLE_USER') %}
                            <a class="btn btn-outline-secondary" href="{{ path('app_equipe_edit', {'id': equipe.id}) }}">Modifier</a>
                        {% endif %}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Pas de données trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/equipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Equipe{% endblock %}

{% block body %}
    <div class="d-flex flex-justify-content-center">
        <h1 class="display-1 border border-dark rounded mx-auto mt-2 p-2">Créer une nouvelle équipe</h1>
    </div>

    {{ include('equipe/_form.html.twig') }}

    
{% endblock %}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/equipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Afficher Equipe{% endblock %}

{% block body %}
    <div class="d-flex flex-justify-content-center">
        <h1 class="display-1 border border-dark rounded mx-auto mt-2 p-2">Afficher Equipe</h1>
    </div>
    <img src= "{{ photo }}">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ equipe.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ equipe.libelle }}</td>
            </tr>
            <tr>
                <th>Entraineur</th>
                <td>{{ equipe.entraineur }}</td>
            </tr>
            <tr>
                <th>Créneaux</th>
                <td>{{ equipe.creneaux }}</td>
            </tr>
            <tr>
                <th>Lien photo</th>
                <td>{{ equipe.urlPhoto }}</td>
            </tr>
            <tr>
                <th>Lien calendrier</th>
                <td>{{ equipe.urlResultCalendrier }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ equipe.commentaire }}</td>
            </tr>
        </tbody>
    </table>
    <div class="d-flex flex-row-reverse px-2 justify-content-space-around">
        {% if is_granted('ROLE_USER') %}
        {{ include('equipe/_delete_form.html.twig') }}
        <a class="btn btn-primary mx-2" href="{{ path('app_equipe_edit', {'id': equipe.id}) }}">Modifier</a>
        {% endif %}
        <a class="btn btn-secondary" href="{{ path('app_equipe_index') }}">Retour à la liste</a>
    </div>
{% endblock %}