sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/src/Entity/Rencontre.php
<?php

namespace App\Entity;

use App\Repository\RencontreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RencontreRepository::class)]
class Rencontre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $domicile_exterieur = null;

    #[ORM\Column(length: 255)]
    private ?string $hote = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_heure = null;

    #[ORM\Column(length: 255)]
    private ?string $gymnase = null;

    #[ORM\Column(length: 255)]
    private ?string $equipe_adverse = null;

    #[ORM\ManyToOne(inversedBy: 'rencontres')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Equipe $equipe_locale = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isDomicileExterieur(): ?bool
    {
        return $this->domicile_exterieur;
    }

    public function setDomicileExterieur(bool $domicile_exterieur): self
    {
        $this->domicile_exterieur = $domicile_exterieur;

        return $this;
    }

    public function getHote(): ?string
    {
        return $this->hote;
    }

    public function setHote(string $hote): self
    {
        $this->hote = $hote;

        return $this;
    }

    public function getDateHeure(): ?\DateTimeInterface
    {
        return $this->date_heure;
    }

    public function setDateHeure(\DateTimeInterface $date_heure): self
    {
        $this->date_heure = $date_heure;

        return $this;
    }

    
    public function getGymnase(): ?string
    {
        return $this->gymnase;
    }

    public function setGymnase(string $gymnase): self
    {
        $this->gymnase = $gymnase;

        return $this;
    }

    public function getEquipeAdverse(): ?string
    {
        return $this->equipe_adverse;
    }

    public function setEquipeAdverse(string $equipe_adverse): self
    {
        $this->equipe_adverse = $equipe_adverse;

        return $this;
    }

    public function getEquipeLocale(): ?Equipe
    {
        return $this->equipe_locale;
    }

    public function setEquipeLocale(?Equipe $equipe_locale): self
    {
        $this->equipe_locale = $equipe_locale;

        return $this;
    }
}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/src/Form/RencontreType.php
<?php

namespace App\Form;

use App\Entity\Rencontre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RencontreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('domicile_exterieur')
            ->add('hote')
            ->add('date_heure')
            ->add('gymnase')
            ->add('equipe_adverse')
            ->add('equipe_locale')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Rencontre::class,
        ]);
    }
}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/src/Controller/RencontreController.php
<?php

namespace App\Controller;

use App\Entity\Rencontre;
use App\Form\RencontreType;
use App\Repository\RencontreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/rencontre')]
class RencontreController extends AbstractController
{
    #[Route('/', name: 'app_rencontre_index', methods: ['GET'])]
    public function index(RencontreRepository $rencontreRepository): Response
    {
        return $this->render('rencontre/index.html.twig', [
            'rencontres' => $rencontreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_rencontre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RencontreRepository $rencontreRepository): Response
    {
        $rencontre = new Rencontre();
        $form = $this->createForm(RencontreType::class, $rencontre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rencontreRepository->save($rencontre, true);

            return $this->redirectToRoute('app_rencontre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rencontre/new.html.twig', [
            'rencontre' => $rencontre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_rencontre_show', methods: ['GET'])]
    public function show(Rencontre $rencontre): Response
    {
        return $this->render('rencontre/show.html.twig', [
            'rencontre' => $rencontre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_rencontre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Rencontre $rencontre, RencontreRepository $rencontreRepository): Response
    {
        $form = $this->createForm(RencontreType::class, $rencontre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rencontreRepository->save($rencontre, true);

            return $this->redirectToRoute('app_rencontre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rencontre/edit.html.twig', [
            'rencontre' => $rencontre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_rencontre_delete', methods: ['POST'])]
    public function delete(Request $request, Rencontre $rencontre, RencontreRepository $rencontreRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rencontre->getId(), $request->request->get('_token'))) {
            $rencontreRepository->remove($rencontre, true);
        }

        return $this->redirectToRoute('app_rencontre_index', [], Response::HTTP_SEE_OTHER);
    }
}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/rencontre/_delete_form.html.twig
<form method="post" action="{{ path('app_rencontre_delete', {'id': rencontre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rencontre.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/rencontre/_form.html.twig
{{ form_start(form) }}
    <div class="form mx-3 my-auto">
        <div class="form-check form-switch">
            {{ form_widget(form.domicile_exterieur, {'attr': {'class': 'form-control form-check-input'}}) }}
            {{ form_label(form.domicile_exterieur) }}
        </div>
        <div class="input-group mb-3">
            {{ form_label(form.hote, null, {'label_attr': {'class': 'input-group-text'}}) }}
            {{ form_widget(form.hote, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group mb-3">
            {{ form_label(form.date_heure, null, {'label_attr': {'class': 'input-group-text'}}) }}
            {{ form_widget(form.date_heure, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="input-group mb-3">
            {{ form_label(form.gymnase, null, {'label_attr': {'class': 'input-group-text'}}) }}
            {{ form_widget(form.gymnase, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="input-group mb-3">
            {{ form_label(form.equipe_adverse, null, {'label_attr': {'class': 'input-group-text'}}) }}
            {{ form_widget(form.equipe_adverse, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="input-group mb-3">
            {{ form_label(form.equipe_locale, null, {'label_attr': {'class': 'input-group-text'}}) }}
            {{ form_widget(form.equipe_locale, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="d-flex flex-row-reverse px-2 justify-content-space-around py-2">
            <button class="btn btn-success d-flex flex-row-reverse mx-2">{{ button_label|default('Save') }}</button>
            <a class="btn btn-secondary" href="{{ path('app_rencontre_index') }}">Retour à la liste</a>
        </div>
    </div>

{{ form_end(form) }}

<script src="https://code.jquery.com/jquery-1.11.3.js"></script>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss'
        });
    });

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/rencontre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Rencontre{% endblock %}

{% block body %}
    <div class="d-flex flex-justify-content-center">
        <h1 class="display-1 border border-dark rounded mx-auto mt-2 p-2">Modifier la Rencontre</h1>
    </div>

    {{ include('rencontre/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/rencontre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des rencontre{% endblock %}

{% block body %}
    <div class="d-flex flex-justify-content-center">
        <h1 class="display-1 border border-dark rounded mx-auto mt-2 p-2">liste des Rencontres</h1>
    </div>

    {% if is_granted('ROLE_USER') %}
        <a class="btn btn-outline-primary py-2 my-3" href="{{ path('app_rencontre_new') }}">Ajouter une nouvelle Rencontre</a>
    {% endif %}

    <table class="table table-striped">
        <thead>
            <tr class="table-primary">
                <th>Id</th>
                <th>Domicile_exterieur</th>
                <th>Hote</th>
                <th>Date_heure</th>
                <th>Gymnase</th>
                <th>Equipe adverse</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for rencontre in rencontres %}
            <tr>
                <td class="align-middle">{{ rencontre.id }}</td>
                <td class="align-middle">{{ rencontre.domicileExterieur ? 'Yes' : 'No' }}</td>
                <td class="align-middle">{{ rencontre.hote }}</td>
                <td class="align-middle">{{ rencontre.dateHeure ? rencontre.dateHeure|date('Y-m-d H:i:s') : '' }}</td>
                <td class="align-middle">{{ rencontre.gymnase }}</td>
                <td class="align-middle">{{ rencontre.equipeAdverse }}</td>
                <td class="align-middle">
                <div class="d-flex flex-column flex-justify-content-center flex-align-item-space-around">
                        <a class="btn btn-outline-primary" href="{{ path('app_rencontre_show', {'id': rencontre.id}) }}">Afficher</a>
                        {% if is_granted('ROLE_USER') %}
                            <a class="btn btn-outline-secondary" href="{{ path('app_rencontre_edit', {'id': rencontre.id}) }}">Modifier</a>
                        {% endif %}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Pas de données trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/rencontre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer Rencontre{% endblock %}

{% block body %}
    <div class="d-flex flex-justify-content-center">
        <h1 class="display-1 border border-dark rounded mx-auto mt-2 p-2">Créer une nouvelle Rencontre</h1>
    </div>

    {{ include('rencontre/_form.html.twig') }}

{% endblock %}

sae-s4-mathon-gardanne-fuma-dessolin-main/sae-s4-mathon-gardanne-fuma-dessolin-main/templates/rencontre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rencontre{% endblock %}

{% block body %}
    <div class="d-flex flex-justify-content-center">
        <h1 class="display-1 border border-dark rounded mx-auto mt-2 p-2">Rencontre</h1>
    </div>

    <table class="table table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ rencontre.id }}</td>
            </tr>
            <tr>
                <th>Domicile extérieur</th>
                <td>{{ rencontre.domicileExterieur ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Hôte</th>
                <td>{{ rencontre.hote }}</td>
            </tr>
            <tr>
                <th>Heure</th>
                <td>{{ rencontre.dateHeure ? rencontre.dateHeure|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Numéro semaine</th>
                <td>{{ rencontre.numSemaine }}</td>
            </tr>
            <tr>
                <th>Numéro journée</th>
                <td>{{ rencontre.numJournee }}</td>
            </tr>
            <tr>
                <th>Gymnase</th>
                <td>{{ rencontre.gymnase }}</td>
            </tr>
            <tr>
                <th>Equipe adverse</th>
                <td>{{ rencontre.equipeAdverse }}</td>
            </tr>
        </tbody>
    </table>
    <div class="d-flex flex-row-reverse px-2 justify-content-space-around">
        {% if is_granted('ROLE_USER') %}
        {{ include('rencontre/_delete_form.html.twig') }}
        <a class="btn btn-primary mx-2" href="{{ path('app_rencontre_edit', {'id': rencontre.id}) }}">Modifier</a>
        {% endif %}
        <a class="btn btn-secondary" href="{{ path('app_rencontre_index') }}">Retour à la liste</a>
    </div>

{% endblock %}